name: Publish to PyPI

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to publish (optional - uses pyproject.toml version if not specified)"
        required: false
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Configure Poetry
        run: poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}

      - name: Update version if specified
        if: ${{ github.event.inputs.version != '' }}
        run: poetry version ${{ github.event.inputs.version }}

      - name: Get package version
        id: get_version
        run: echo "version=$(poetry version -s)" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: poetry install --no-dev

      - name: Build package
        run: poetry build

      - name: Check package
        run: |
          poetry run pip install twine
          poetry run twine check dist/*

      - name: Publish to PyPI
        run: poetry publish

      - name: Create GitHub Release
        if: success()
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          release_name: Release v${{ steps.get_version.outputs.version }}
          body: |
            Published omar6995-browserforge v${{ steps.get_version.outputs.version }} to PyPI

            Changes in this release:
            - Manual release triggered via GitHub Actions
          draft: false
          prerelease: false
